[package]
name = "profiler_builtins"
version = "0.0.0"
edition = "2021"

[lib]
test = false
bench = false
doc = false

[dependencies]
core = { path = "../core" }
compiler_builtins = { version = "0.1.0", features = ['rustc-dep-of-std'] }

[build-dependencies]
# FIXME: updates past a certain point haven't been able to merge successfully.
# See rust-lang/rust#130720.
cc = "=1.0.99"
