cargo-features = ["edition2024"]

[package]
name = "rustc_index_macros"
version = "0.0.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.9", features = ["full"] }
proc-macro2 = "1"
quote = "1"

[features]
default = ["nightly"]
nightly = []
