[package]
name = "windows-targets"
description = "A drop-in replacement for the real windows-targets crate for use in std only."
version = "0.0.0"
edition = "2021"

[features]
# Enable using Windows import libraries instead of raw-dylib.
windows_use_import_libs = []
