cargo-features = ["edition2024"]

[package]
name = "rustc_feature"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
rustc_data_structures = { path = "../rustc_data_structures" }
rustc_span = { path = "../rustc_span" }
# tidy-alphabetical-end
